before:
  hooks:
    - make clean
    - sh -c "NEXT_PUBLIC_VERSION={{ .Version}} make build-admin"
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/hetty
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: hettysoft
      name: homebrew-tap
    folder: Formula
    homepage:  https://hetty.xyz
    description: An HTTP toolkit for security research.
    license: MIT
    commit_author:
      name: David Stotijn
      email: dstotijn@gmail.com
    test: |
      system "#{bin}/hetty -v"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
